config/routes.rb
Rails.application.routes.draw do
  get 'top' => 'home#top'
  root :to => 'home#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
      @books = Book.all
      @book = Book.new
  end

  def show
      @book = Book.find(params[:id])
  end

  def new
      @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :index
    end
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
    end
  end

  private
  def book_params
      params.require(:book).permit(:title, :body)
  end
 end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_for(@book) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %><br>
    <%= f.submit 'Update Book' %><br>
<% end %>

<%= link_to "Show", book_path(@book) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>
    <table>
      <thead>
        <% if flash[:notice] %>
         <p><%= flash[:notice] %></p>
        <% end %>

        <tr>
          <th>Title</th>
          <th>Body</th>
        </tr>
        <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
        <td>
        <%= link_to "Show", book_path(book.id) %>
        <%= link_to "Edit", edit_book_path(book.id) %>
        <%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
        </td>
        </tr>
        <% end %>
      </thead>
</table>

<h1>New Book</h1>
<%= form_for(@book) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %><br>

    <%= f.submit 'Create Book' %>

<% end %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= form_for(@book) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %><br>

    <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<p class="single-text">
	<strong>Title:</strong><%= @book.title %><br>
<p class="single-text">
    <strong>Body:</strong><%= @book.body %>

</p>
<section>
<%= link_to "Edit", edit_book_path(@book) %>
<%= link_to "Back", books_path %></section>

app/views/home/top.html.erb
<h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<a href="/books">start</a>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
  	　	<h2><%= model.errors.count %>error</h2>
     <ul>
      <% model.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>